/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CollateralToken } from "./CollateralToken";
export type { Lock } from "./Lock";
export type { SyntheticAsset } from "./SyntheticAsset";
