/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CollateralToken__factory } from "./CollateralToken__factory";
export { Lock__factory } from "./Lock__factory";
export { SyntheticAsset__factory } from "./SyntheticAsset__factory";
